# Generated by Django 4.1.5 on 2023-01-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='GST_NUMBER',
        ),
        migrations.AddField(
            model_name='myuser',
            name='gst_no',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
