# Generated by Django 4.1.5 on 2023-01-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
