# Generated by Django 4.1.5 on 2023-02-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart_items',
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_option',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('Razorpay', 'Razorpay'), ('cash On delivery', 'cash On delivery')], max_length=30, null=True),
        ),
    ]
