# Generated by Django 4.1.5 on 2023-02-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orders_cart_items_alter_orders_payment_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='vehicles',
        ),
    ]
