# Generated by Django 4.1.5 on 2023-02-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orders_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_units',
            field=models.IntegerField(default=0),
        ),
    ]
