# Generated by Django 4.1.5 on 2023-03-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_total_units_orders_no_of_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='no_of_items',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
