# Generated by Django 4.1.5 on 2023-03-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orders_no_of_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('order processing', 'order processing'), ('Shipped', 'Shipped'), ('Out_for_delivery', 'Out_for_delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Confirmed', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordervehicle',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('order processing', 'order processing'), ('Shipped', 'Shipped'), ('Out_for_delivery', 'Out_for_delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Confirmed', max_length=30),
        ),
    ]
