# Generated by Django 4.1.5 on 2023-02-07 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='price',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='remaining',
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='photos/vehicles')),
                ('image2', models.ImageField(upload_to='photos/vehicles')),
                ('image3', models.ImageField(upload_to='photos/vehicles')),
                ('price', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.vehicles')),
            ],
        ),
    ]
