# Generated by Django 4.1.5 on 2023-02-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_vehicles_image1_remove_vehicles_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='color',
            field=models.CharField(default='#FF0000', max_length=100),
        ),
    ]
