# Generated by Django 4.1.5 on 2023-03-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
