# Generated by Django 4.1.5 on 2023-02-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartapp', '0003_coupon_created_date_coupon_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='expiry_date',
        ),
    ]
