# Generated by Django 4.1.5 on 2023-06-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gif_image',
            field=models.URLField(default=None, null=True),
        ),
    ]
