# Generated by Django 4.1.5 on 2023-02-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.CharField(default='Main', max_length=100),
        ),
    ]
