# Generated by Django 4.1.5 on 2023-03-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_banner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='texts',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
